import type { Metadata } from "next";
import { Inter, Poppins, Public_Sans, Outfit } from "next/font/google";
import "@/styles/index.scss";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

const public_Sans = Public_Sans({
  subsets: ["latin"],
  variable: "--public_sans",
  weight: ["400", "500", "600", "700"],
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--outfit",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${inter.variable} ${poppins.variable} ${public_Sans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
